### ISSUE TITLE
I get this error

### ISSUE THREAD

**Issue by slidigeek** [SirTenzin/OTP-Bot#18]
I get this error.
What is the cause?
When i run

$ node otp.js
Twilio Client app HTTP server running at http://127.0.0.1:3000
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'libphonenumber-js'
Require stack:
- C:\Users\slidi\Downloads\OTP-Bot-master\OTP-Bot-master\bot\src\commands\otp\CoinbaseCommand.js
- C:\Users\slidi\Downloads\OTP-Bot-master\OTP-Bot-master\bot\src\utils\registry.js
- C:\Users\slidi\Downloads\OTP-Bot-master\OTP-Bot-master\bot\src\index.js
- C:\Users\slidi\Downloads\OTP-Bot-master\OTP-Bot-master\otp.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\slidi\Downloads\OTP-Bot-master\OTP-Bot-master\bot\src\commands\otp\CoinbaseCommand.js:4:30)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\slidi\\Downloads\\OTP-Bot-master\\OTP-Bot-master\\bot\\src\\commands\\otp\\CoinbaseCommand.js',
    'C:\\Users\\slidi\\Downloads\\OTP-Bot-master\\OTP-Bot-master\\bot\\src\\utils\\registry.js',
    'C:\\Users\\slidi\\Downloads\\OTP-Bot-master\\OTP-Bot-master\\bot\\src\\index.js',
    'C:\\Users\\slidi\\Downloads\\OTP-Bot-master\\OTP-Bot-master\\otp.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
![otperror](https://user-images.githubusercontent.com/97806367/149635556-89194710-37cf-493b-a1cb-068d596b2b24.PNG)
.

**Comment by c-for-coder** [comment]
same with me

**Comment by donsinoe** [comment]
Please how do we install the modules

**Comment by MosaabDevv** [comment]
npm i libphonenumber-js

**Comment by slidigeek** [comment]
Ok done i just installed the modules and run the bot but how do i know the bot is running and how do i use it?

**Comment by yournewpapi0604** [comment]
> Ok done i just installed the modules and run the bot but how do i know the bot is running and how do i use it?

That has to be single handedly the dumbest question ever. Why attempt if you don’t even know what your doing. Like this is the easiest part

**Comment by slidigeek** [comment]
> > Ok done i just installed the modules and run the bot but how do i know the bot is running and how do i use it?
> 
> That has to be single handedly the dumbest question ever. Why attempt if you don’t even know what your doing. Like this is the easiest part

Well even the an adult has to be a baby before he turns to an adult.
I ask the dumbest question today so that i can give wise answers in the future to another person dumb question

**Comment by yournewpapi0604** [comment]
> npm i libphonenumber-js

Hey can you check my new issue, not sure whats going on there

**Comment by MosaabDevv** [comment]
DM me for a setup Mosaab#7777
