### ISSUE TITLE
While running I got this error please help me in this

### ISSUE THREAD

**Issue by pushpenderkadian** [SirTenzin/OTP-Bot#20]
![image](https://user-images.githubusercontent.com/75625809/152645691-f4eae987-012a-422b-a684-e5bcbf116bba.png)

Please help me

**Comment by MosaabDevv** [comment]
Hi, your bot token is missing Client Intents. Please enable in [in ](https://discord.com/developers/applications) 

![image](https://user-images.githubusercontent.com/93290137/153310380-5e0cbd29-7adc-4a60-a10f-29e269b0ab95.png)
