### ISSUE TITLE
Helping people set the bot up

### ISSUE THREAD

**Issue by Zeph4455** [SirTenzin/OTP-Bot#23]
I charge 65 for a whole fixed up source with a upgraded twilio account and a tutorial on how to use the bot

telegram : @TheZankz

**Comment by SMACK12312** [comment]
DONT LISTEN TO THIS FRAUD MAN. HE MADE ME SEND THE MONEY IN CRYPTO AND  NOW HE DELETED OUR ENTIRE THREAD AND WONT RESPOND

**Comment by cuviermarcel14** [comment]
Smh bad business

**Comment by SirTenzin** [comment]
L
