### ISSUE TITLE
How to start the bot / bot commands also give ur contact info

### ISSUE THREAD

**Issue by cheemzboi** [SirTenzin/OTP-Bot#30]
i have setted up the bot correctly now when i run the last yarn command and got all details of the bot and channel on discord 

now how do i proceed further by authing users and testing commands pls tell 
also if u have a discord id or telegram id please drop it too 

it will be very helpful thanks

**Comment by Melloz791** [comment]
i got it working , just give me an error when trying to call

**Comment by sudOcrypt** [comment]
how did you get it working

**Comment by theyknowdev** [comment]
> i have setted up the bot correctly now when i run the last yarn command and got all details of the bot and channel on discord
> 
> now how do i proceed further by authing users and testing commands pls tell also if u have a discord id or telegram id please drop it too
> 
> it will be very helpful thanks

is there any vids to hlep me set it up

**Comment by theyknowdev** [comment]
> i got it working , just give me an error when trying to call

can you tell me how you got it working cause i need help
