### ISSUE TITLE
SCAM

### ISSUE THREAD

**Issue by Microthefirst** [SirTenzin/OTP-Bot#31]
Running source : $65
Auth system in bot : $100
Auth sys/custom scripts : $130
Auth sys/custom scripts/number spoof : $220
Message me on tele @Microthefirst

**Comment by darkhacknet** [comment]
> Running source : $65 Auth system in bot : $100 Auth sys/custom scripts : $130 Auth sys/custom scripts/number spoof : $220 Message me on tele @Microthefirst

Are you hungry bro ? hahaah !

**Comment by SirTenzin** [comment]
Known scammer dont pay for the source its free
